Vagrant.configure("2") do |config|
  config.vm.define "pick-linuxtips" do |pick_linuxtips|
    pick_linuxtips.vm.box = "ubuntu/jammy64"
    pick_linuxtips.vm.hostname = "pick-linuxtips"
    pick_linuxtips.vm.provision "shell", path: "script.sh", privileged: false
   end
end